/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import java.awt.Frame;
import java.sql.Connection;
import javax.swing.JDialog;
import javax.swing.JFrame;
import javax.swing.SwingUtilities;

/**
 *
 * @author alary
 */
public class CategoriasPanel extends javax.swing.JPanel {
private Connection conexion;
    /**
     * Creates new form CategoriasPanel
     */
    public CategoriasPanel(Connection conexion) {
        this.conexion = conexion;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnHerramientas = new javax.swing.JButton();
        btnPinturas = new javax.swing.JButton();
        btnMaterialesConstruccion = new javax.swing.JButton();
        btnElectricidad = new javax.swing.JButton();
        btnFontaneria = new javax.swing.JButton();
        btnJardineria = new javax.swing.JButton();
        btnSeguridad = new javax.swing.JButton();
        btnIluminacion = new javax.swing.JButton();
        btnPegamentosAdhesivos = new javax.swing.JButton();
        btnFerreteriaGeneral = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(940, 550));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 51));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel11.setText("Categorias");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 58, Short.MAX_VALUE)
        );

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, -1));

        jLabel1.setText("Herramientas");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, -1));

        jLabel2.setText("Pinturas");
        add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 200, -1, -1));

        jLabel3.setText("Materiales de Construcción");
        add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 200, -1, -1));

        jLabel4.setText("Electricidad");
        add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 200, -1, -1));

        jLabel5.setText("Fontanería");
        add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 370, -1, -1));

        jLabel6.setText("Jardinería");
        add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 370, -1, 10));

        jLabel7.setText("Seguridad");
        add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 370, -1, -1));

        jLabel8.setText("Iluminación");
        add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 370, -1, -1));

        jLabel9.setText("Adhesivos y Selladores");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, -1));

        jLabel10.setText("Ferretería General");
        add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 530, -1, -1));

        btnHerramientas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/caja-de-herramientas.png"))); // NOI18N
        btnHerramientas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHerramientasActionPerformed(evt);
            }
        });
        add(btnHerramientas, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 70, 130, 130));

        btnPinturas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/bote-de-pintura.png"))); // NOI18N
        btnPinturas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPinturasActionPerformed(evt);
            }
        });
        add(btnPinturas, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 140, 130));

        btnMaterialesConstruccion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/materiales-de-construccioncat.png"))); // NOI18N
        btnMaterialesConstruccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMaterialesConstruccionActionPerformed(evt);
            }
        });
        add(btnMaterialesConstruccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 70, 140, 130));

        btnElectricidad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/instalacion.png"))); // NOI18N
        btnElectricidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnElectricidadActionPerformed(evt);
            }
        });
        add(btnElectricidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 70, 140, 130));

        btnFontaneria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/mantenimiento-de-fontaneria.png"))); // NOI18N
        btnFontaneria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFontaneriaActionPerformed(evt);
            }
        });
        add(btnFontaneria, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 130, 140));

        btnJardineria.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/jardineria.png"))); // NOI18N
        btnJardineria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnJardineriaActionPerformed(evt);
            }
        });
        add(btnJardineria, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 230, 140, 140));

        btnSeguridad.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/proteger.png"))); // NOI18N
        btnSeguridad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeguridadActionPerformed(evt);
            }
        });
        add(btnSeguridad, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 230, 140, 140));

        btnIluminacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/lampara-de-techo.png"))); // NOI18N
        btnIluminacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIluminacionActionPerformed(evt);
            }
        });
        add(btnIluminacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 230, 140, 140));

        btnPegamentosAdhesivos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/adhesivos.png"))); // NOI18N
        btnPegamentosAdhesivos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPegamentosAdhesivosActionPerformed(evt);
            }
        });
        add(btnPegamentosAdhesivos, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 390, 140, 140));

        btnFerreteriaGeneral.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/empulgueras.png"))); // NOI18N
        btnFerreteriaGeneral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFerreteriaGeneralActionPerformed(evt);
            }
        });
        add(btnFerreteriaGeneral, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 390, 140, 140));
    }// </editor-fold>//GEN-END:initComponents

    private void btnHerramientasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHerramientasActionPerformed
        // TODO add your handling code here:
        java.awt.Window parentWindow = SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof javax.swing.JFrame) {
            TablaHerramientas tablaHerramientas = new TablaHerramientas((javax.swing.JFrame) parentWindow, true);
            tablaHerramientas.setLocationRelativeTo(parentWindow); // Centrar el JDialog relativo al JFrame padre
            tablaHerramientas.setVisible(true);
        }
    }//GEN-LAST:event_btnHerramientasActionPerformed

    private void btnPinturasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPinturasActionPerformed
        // TODO add your handling code here:
        java.awt.Window parentWindow = SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof javax.swing.JFrame) {
            TablaPinturas tablaPinturas = new TablaPinturas((javax.swing.JFrame) parentWindow, true);
            tablaPinturas.setLocationRelativeTo(parentWindow); // Centrar el JDialog relativo al JFrame padre
            tablaPinturas.setVisible(true);
        }
    }//GEN-LAST:event_btnPinturasActionPerformed

    private void btnMaterialesConstruccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMaterialesConstruccionActionPerformed
        // TODO add your handling code here:
        java.awt.Window parentWindow = SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof javax.swing.JFrame) {
            TablaMaterialesConstruccion tablaMaterialesConstruccion = new TablaMaterialesConstruccion((javax.swing.JFrame) parentWindow, true);
            tablaMaterialesConstruccion.setLocationRelativeTo(parentWindow); // Centrar el JDialog relativo al JFrame padre
            tablaMaterialesConstruccion.setVisible(true);
        }
    }//GEN-LAST:event_btnMaterialesConstruccionActionPerformed

    private void btnElectricidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnElectricidadActionPerformed
        // TODO add your handling code here:
         java.awt.Window parentWindow = SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof javax.swing.JFrame) {
            TablaElectricidad tablaElectricidad = new TablaElectricidad((javax.swing.JFrame) parentWindow, true);
            tablaElectricidad.setLocationRelativeTo(parentWindow); // Centrar el JDialog relativo al JFrame padre
            tablaElectricidad.setVisible(true);
        }
    }//GEN-LAST:event_btnElectricidadActionPerformed

    private void btnFontaneriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFontaneriaActionPerformed
        // TODO add your handling code here:
         java.awt.Window parentWindow = SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof javax.swing.JFrame) {
            TablaFontaneria tablaFontaneria = new TablaFontaneria((javax.swing.JFrame) parentWindow, true);
            tablaFontaneria.setLocationRelativeTo(parentWindow); // Centrar el JDialog relativo al JFrame padre
            tablaFontaneria.setVisible(true);
        }
    }//GEN-LAST:event_btnFontaneriaActionPerformed

    private void btnJardineriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnJardineriaActionPerformed
        // TODO add your handling code here:
         java.awt.Window parentWindow = SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof javax.swing.JFrame) {
            TablaJardineria tablaJardineria = new TablaJardineria((javax.swing.JFrame) parentWindow, true);
            tablaJardineria.setLocationRelativeTo(parentWindow); // Centrar el JDialog relativo al JFrame padre
            tablaJardineria.setVisible(true);
        }
    }//GEN-LAST:event_btnJardineriaActionPerformed

    private void btnSeguridadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeguridadActionPerformed
        // TODO add your handling code here:
         java.awt.Window parentWindow = SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof javax.swing.JFrame) {
            TablaSeguridad tablaSeguridad = new TablaSeguridad((javax.swing.JFrame) parentWindow, true);
            tablaSeguridad.setLocationRelativeTo(parentWindow); // Centrar el JDialog relativo al JFrame padre
            tablaSeguridad.setVisible(true);
        }
    }//GEN-LAST:event_btnSeguridadActionPerformed

    private void btnIluminacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIluminacionActionPerformed
        // TODO add your handling code here:
         java.awt.Window parentWindow = SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof javax.swing.JFrame) {
            TablaIluminacion tablaIluminacion = new TablaIluminacion((javax.swing.JFrame) parentWindow, true);
            tablaIluminacion.setLocationRelativeTo(parentWindow); // Centrar el JDialog relativo al JFrame padre
            tablaIluminacion.setVisible(true);
        }
    }//GEN-LAST:event_btnIluminacionActionPerformed

    private void btnPegamentosAdhesivosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPegamentosAdhesivosActionPerformed
        // TODO add your handling code here:
         java.awt.Window parentWindow = SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof javax.swing.JFrame) {
            TablaAdhesivosySelladores tablaAdhesivosySelladores = new TablaAdhesivosySelladores((javax.swing.JFrame) parentWindow, true);
            tablaAdhesivosySelladores.setLocationRelativeTo(parentWindow); // Centrar el JDialog relativo al JFrame padre
            tablaAdhesivosySelladores.setVisible(true);
        }
    }//GEN-LAST:event_btnPegamentosAdhesivosActionPerformed

    private void btnFerreteriaGeneralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFerreteriaGeneralActionPerformed
        // TODO add your handling code here:
         java.awt.Window parentWindow = SwingUtilities.getWindowAncestor(this);
        if (parentWindow instanceof javax.swing.JFrame) {
            TablaFerreteriaGeneral tablaFerreteriaGeneral = new TablaFerreteriaGeneral((javax.swing.JFrame) parentWindow, true);
            tablaFerreteriaGeneral.setLocationRelativeTo(parentWindow); // Centrar el JDialog relativo al JFrame padre
            tablaFerreteriaGeneral.setVisible(true);
        }
    }//GEN-LAST:event_btnFerreteriaGeneralActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnElectricidad;
    private javax.swing.JButton btnFerreteriaGeneral;
    private javax.swing.JButton btnFontaneria;
    private javax.swing.JButton btnHerramientas;
    private javax.swing.JButton btnIluminacion;
    private javax.swing.JButton btnJardineria;
    private javax.swing.JButton btnMaterialesConstruccion;
    private javax.swing.JButton btnPegamentosAdhesivos;
    private javax.swing.JButton btnPinturas;
    private javax.swing.JButton btnSeguridad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
