/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

/**
 *
 * @author alary
 */
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

import javax.swing.*;
import java.awt.*;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.Map;
import modelo.VentaDAO;
public class DashboardMainPanel extends javax.swing.JPanel {
     private Connection conexion;
     private VentaDAO ventaDAO;

    /**
     * Creates new form DashboardMainPanel
     */
     public DashboardMainPanel(Connection conexion) {
        this.conexion = conexion;
        this.ventaDAO = new VentaDAO(conexion);
        initComponents();
        agregarGrafico();
    }
    private void agregarGrafico() {
        DefaultCategoryDataset dataset = crearDataset();
        JFreeChart chart = ChartFactory.createBarChart(
                "Productos Más Vendidos",
                "Producto",
                "Cantidad Vendida",
                dataset,
                PlotOrientation.VERTICAL,
                true,
                true,
                false);

        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setPreferredSize(new Dimension(800, 600));

        setLayout(new BorderLayout());
        add(chartPanel, BorderLayout.CENTER);
    }

    private DefaultCategoryDataset crearDataset() {
        DefaultCategoryDataset dataset = new DefaultCategoryDataset();
        try {
            Map<String, Integer> productosMasVendidos = ventaDAO.obtenerProductosMasVendidos();
            for (Map.Entry<String, Integer> entry : productosMasVendidos.entrySet()) {
                dataset.addValue(entry.getValue(), "Productos", entry.getKey());
            }
        } catch (SQLException e) {
            e.printStackTrace();
        }
        return dataset;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 940, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 550, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
